pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: 'jenkins_git_cred', 
                url: 'https://github.com/suhasdombale123/Jenkins-Zero-To-Hero-Practice.git',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    dir('python-jenkins-argocd-k8s'){
                        sh '''
                        echo 'Buid Docker Image'
                        docker build -t suhasdombale123/jenkins-vote-app:${BUILD_NUMBER} .
                        '''
                    }
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push suhasdombale123/jenkins-vote-app:${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        // stage('Checkout K8S manifest SCM'){
        //     steps {
        //         git credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', 
        //         url: 'https://github.com/iam-veeramalla/cicd-demo-manifests-repo.git',
        //         branch: 'main'
        //     }
        // }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    dir('python-jenkins-argocd-k8s/deploy'){
                        withCredentials([usernamePassword(credentialsId: 'jenkins_git_cred', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                            sh '''
                            cat deploy.yaml
                            sed -i "s/v1/${BUILD_NUMBER}/g" deploy.yaml
                            cat deploy.yaml
                            git config --global user.email "suhasdombale123@gmail.com"
                            git config --global user.name "Suhas Dombale"
                            git add deploy.yaml
                            git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                            git remote -v
                            git push --set-upstream origin main
                            '''                        
                        }
                    }
                }
            }
        }
    }
}
